### ISSUE TITLE
Can i do Multiple LOGIN here like User Login and Admin Login both are separate?

### ISSUE THREAD

**Issue by patel405nishant** [DavideViolante/Angular-Full-Stack#101]
I have already use this code and applied lots of changes using this code. Now we have requirement for making separate login one for Admin section and User section using same Auth code with token.

Can you please let me know it is possible or not? If yes the please let me know about hot set two AUTH with token for User and Admin login.

Thank You!

**Comment by DavideViolante** [comment]
Just create another login page where only admins can login. I think you can do it duplicating the login backend method in user.ts and make another one that finds by email and role instead of only email.
