### ISSUE TITLE
How to debug the app in VS Code?

### ISSUE THREAD

**Issue by im-omi** [DavideViolante/Angular-Full-Stack#102]
Are there any special considerations needed when creating the launch.json file to run in debug mode on VS Code?

**Comment by DerejeKitaw** [comment]
first turn on "sourceMap": true in tsconfig.json for the server.

run tsc to generate map file

then modify launch.json file to:

`    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/server/app.ts",
            "cwd": "${workspaceRoot}",
            "outFiles": [
                "${workspaceRoot}/dist/server/app.js"
            ],
            "skipFiles": [
                "${workspaceRoot}/node_modules/**/*.js"
            ],
            "sourceMaps": true,
            "console": "externalTerminal"
        }
    ]`

**Comment by rijine** [comment]
How to configure debug with Webstorm / Vscode ?
