### ISSUE TITLE
Serving static files...images

### ISSUE THREAD

**Issue by gbardwell** [DavideViolante/Angular-Full-Stack#111]
Hi David,

I an trying to serve static images... from a /public/images directory.

This will work...http://localhost:3000

But nothing else. Paths are relative to :4200 delivered via a scr="..." or a [scr]="..."

No images are served.

No modification I have tried to server/app.ts work.

Thanks,
Greg

**Comment by billbarni** [comment]
When you compile the frontend (using `ng build`) the static files are stored in the public folder and you should then be able to access those files from the `localhost:3000`.
If you add images to your frontend folder as your assets, they also should be copied to that folder during build.

**Comment by DavideViolante** [comment]
The static files must be located in `client/assets` folder.
Added this info to the [Wiki](https://github.com/DavideViolante/Angular-Full-Stack/wiki) since it seems to be a popular question.

**Comment by cenkozan** [comment]
May I ask, do I have to reach those files like this: `localhost:port/assets/filename.file`. Is there a way to loose the "assets" part? I am trying to import a template but I can't touch its folder structure,

**Comment by DavideViolante** [comment]
Try editing this line: https://github.com/DavideViolante/Angular-Full-Stack/blob/master/.angular-cli.json#L11
