### ISSUE TITLE
Noobie question - How do I use custom types in the client?

### ISSUE THREAD

**Issue by cenkozan** [DavideViolante/Angular-Full-Stack#114]
I have added some custom types. I am always getting the below error on the client side:

```No value accessor for form control with unspecified name attribute```

Please help.

**Comment by cenkozan** [comment]
Example: I have a custom type called Event. 
```export class MyEvent {
  id: number;
  title: string;
  start: string;
  end: string;
  allDay: boolean = true;
}
```
Whenever I try to use something like: 

```[(ngModel)]="event.allDay"```
It throws the above error.

**Comment by DavideViolante** [comment]
Maybe `event` is a special keyword, try to use a different name.

**Comment by dougal83** [comment]
I believe @DavideViolante is correct.  The 'event' variable is used by most browsers as a global keyword and is best avoided. ie: window.event in the DOM for IE.

**Comment by cenkozan** [comment]
Thank you guys, I am getting another error now! (happy and sad :P)
