### ISSUE TITLE
Heroku Deployment not working

### ISSUE THREAD

**Issue by mattmcardle** [DavideViolante/Angular-Full-Stack#115]
I keep getting the following error in my Heroku logs:
Error: Cannot find module 'body-parser'

I'm new to Heroku so it could be an issue with my application set up there, is there anything I need to add on my Heroku application to make it pick up the node modules? I can see it installing the node modules as part of the deployment process.

**Comment by DavideViolante** [comment]
I tried to deploy to Heroku just now and it worked. Are you sure you followed every single step of the readme? In particular `npm i` before `ng build ...`

**Comment by mattmcardle** [comment]
My bad, I had an error in my package.json that was causing it the npm install step to fail. Thanks.
