### ISSUE TITLE
Adding new collection

### ISSUE THREAD

**Issue by cjfarnold** [DavideViolante/Angular-Full-Stack#117]
I tried adding a new collection in the db directly and tried accessing by creating a model and controller but am not able to access the data it always returns a blank value when I access the api directly, is there something wrong I am doing

**Comment by DavideViolante** [comment]
Maybe show us the code, we cannot guess what you wrote and where is the problem.

**Comment by cjfarnold** [comment]
Hi David, I have included the code that I am using
controller code
`import Blog from '../models/blog';
import BaseCtrl from './base';

export default class BlogCtrl extends BaseCtrl {
  model = Blog;
}`
model code
`import * as mongoose from 'mongoose';


const blogSchema = new mongoose.Schema({
  TopicId: Number,
  TopicOwner: String,
  TopicHeader: String,
  TopicQuotes1: String,
  TopicQuotes2: String,
  TopicContentP1: String,
  TopicContentP2: String,
  CodeSnipits: String,
  TopicConversation: {
    VisitorName: String,
    Comments: {
      CommentsText:String,
      VisitorReplyName:String,
      VisitorReplyCommentsText:String,
      TopicOwnerReplyComments:String
    }
  }
});

const Blog = mongoose.model('Blog', blogSchema);`
routes.ts
`  router.route('/blog').get(blogCtrl.getAll);`
