### ISSUE TITLE
Deployment failed

### ISSUE THREAD

**Issue by matthieumarais** [DavideViolante/Angular-Full-Stack#129]
Hello,
I can't manage to deploy. I have a bug when installing on my vps.
I need help plz.

package.json

"name": "angular2-full-stack",
    "version": "4.2.4",
    "license": "MIT",
    "author": "Davide Violante",
    "description": "Angular Full Stack project built using Angular 2+, Express, Mongoose and Node.",
    "angular-cli": {},
    "engines": {
        "node": "6.11.4",
        "npm": "3.10.10"
    },
    "scripts": {
        "ng": "ng",
        "build": "ng build",
        "start": "node dist/server/app.js",
        "predev": "tsc -p server",
        "dev": "concurrently \"mongod\" \"ng serve -pc proxy.conf.json --open\" \"tsc -w -p server\" \"nodemon dist/server/app.js\"",
        "prod": "concurrently \"mongod\" \"ng build -aot -prod && tsc -p server && node dist/server/app.js\"",
        "test": "ng test",
        "testbe": "tsc -p server && mocha dist/server/test --exit",
        "lint": "ng lint",
        "lintbe": "tslint server/**/**.ts{,x}",
        "e2e": "ng e2e",
        "postinstall": "tsc -p server && ng build -aot -prod"
    },
    "private": true,
    "dependencies": {
        "@angular/cli": "1.4.7",
        "@angular/compiler-cli": "^4.2.4",
        "@types/jasmine": "~2.5.53",
        "@types/node": "~6.0.60",
        "chai": "^4.1.2",
        "chai-http": "^3.0.0",
        "@agm/core": "^1.0.0-beta.2",
        "@angular/common": "^4.2.4",
        "@angular/compiler": "^4.2.4",
        "@angular/core": "^4.2.4",
        "@angular/forms": "^4.2.4",
        "@angular/http": "^4.2.4",
        "@angular/platform-browser": "^4.2.4",
        "@angular/platform-browser-dynamic": "^4.2.4",
        "@angular/router": "^4.2.4",
        "@types/googlemaps": "^3.29.2",
        "angular-particle": "^1.0.4",
        "angular2-jwt": "^0.2.3",
        "bcryptjs": "^2.4.3",
        "body-parser": "^1.18.2",
        "bootstrap": "4.0.0-alpha.5",
        "core-js": "^2.5.1",
        "dotenv": "^4.0.0",
        "express": "^4.16.2",
        "font-awesome": "^4.7.0",
        "jquery": "^3.2.1",
        "jsonwebtoken": "^8.1.0",
        "mongoose": "^4.12.1",
        "morgan": "^1.9.0",
        "rxjs": "^5.4.2",
        "tether": "1.4.0",
        "zone.js": "^0.8.14",
        "typescript": "~2.3.3"
    },
    "devDependencies": {
        "@angular/language-service": "^4.2.4",
        "@types/express": "^4.0.37",
        "@types/jasminewd2": "~2.0.2",
        "codelyzer": "~3.2.0",
        "concurrently": "^3.3.0",
        "jasmine-core": "~2.6.2",
        "jasmine-spec-reporter": "~4.1.0",
        "karma": "~1.7.0",
        "karma-chrome-launcher": "~2.1.1",
        "karma-cli": "~1.0.1",
        "karma-coverage-istanbul-reporter": "^1.2.1",
        "karma-jasmine": "~1.1.0",
        "karma-jasmine-html-reporter": "^0.2.2",
        "mocha": "^4.0.1",
        "nodemon": "1.11.0",
        "protractor": "~5.1.2",
        "ts-node": "~3.2.0",
        "tslint": "~5.7.0"
    }
}

when i send 
git push dokku master ( i use dokku but it the same thing)

...
> angular2-full-stack@4.2.4 postinstall /tmp/build
       > tsc -p server && ng build -aot -prod

       /tmp/build/node_modules/@ngtools/json-schema/src/schema-tree.js:226
       this._children[name] = this._createChildProperty(name, value ? value[name] : undefined, forward ? forward.children[name] : null, propertySchema);
       ^

       TypeError: Cannot read property 'glob' of null
       at ObjectSchemaTreeNode._set (/tmp/build/node_modules/@ngtools/json-schema/src/schema-tree.js:226:131)
       at new ObjectSchemaTreeNode (/tmp/build/node_modules/@ngtools/json-schema/src/schema-tree.js:211:14)
       at OneOfSchemaTreeNode._createChildProperty (/tmp/build/node_modules/@ngtools/json-schema/src/schema-tree.js:150:26)
       at OneOfSchemaTreeNode._typesPrototype.schema.oneOf.map (/tmp/build/node_modules/@ngtools/json-schema/src/schema-tree.js:163:25)
       at Array.map (native)
       at OneOfSchemaTreeNode (/tmp/build/node_modules/@ngtools/json-schema/src/schema-tree.js:162:48)
       at ArraySchemaTreeNode._createChildProperty (/tmp/build/node_modules/@ngtools/json-schema/src/schema-tree.js:150:26)
       at ArraySchemaTreeNode._set (/tmp/build/node_modules/@ngtools/json-schema/src/schema-tree.js:288:39)
       at new ArraySchemaTreeNode (/tmp/build/node_modules/@ngtools/json-schema/src/schema-tree.js:269:14)
       at ObjectSchemaTreeNode._createChildProperty (/tmp/build/node_modules/@ngtools/json-schema/src/schema-tree.js:150:26)

       npm ERR! Linux 4.4.0-81-generic
       npm ERR! argv "/tmp/build/.heroku/node/bin/node" "/tmp/build/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build/.npmrc"
       npm ERR! node v6.11.4
       npm ERR! npm  v3.10.10
       npm ERR! code ELIFECYCLE
       npm ERR! angular2-full-stack@4.2.4 postinstall: `tsc -p server && ng build -aot -prod`
       npm ERR! Exit status 1
       npm ERR!
       npm ERR! Failed at the angular2-full-stack@4.2.4 postinstall script 'tsc -p server && ng build -aot -prod'.
       npm ERR! Make sure you have the latest version of node.js and npm installed.
       npm ERR! If you do, this is most likely a problem with the angular2-full-stack package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     tsc -p server && ng build -aot -prod
       npm ERR! You can get information on how to open an issue for this project with:
       npm ERR!     npm bugs angular2-full-stack
       npm ERR! Or if that isn't available, you can get their info via:
       npm ERR!     npm owner ls angular2-full-stack
       npm ERR! There is likely additional logging output above.

       npm ERR! Please include the following file with any support request:
       npm ERR!     /tmp/build/npm-debug.log

-----> Build failed
...

**Comment by DavideViolante** [comment]
Seems to be a common problem with angular cli:
https://github.com/angular/angular-cli/issues/4919
https://www.google.it/search?q=TypeError%3A+Cannot+read+property+%27glob%27+of+null

**Comment by DavideViolante** [comment]
This should be solved, or try https://github.com/angular/angular-cli/issues/4919#issuecomment-300326004
