### ISSUE TITLE
Uploading images

### ISSUE THREAD

**Issue by AlexandrZl** [DavideViolante/Angular-Full-Stack#132]
I created a functionality for uploading some images and `assets/images` folder for them, but after uploading an image I couldn't get it because the server returned a 404 error though after restarting `npm run start` command an image was available, so where should I store images and how can I fix it?

**Comment by Thavarajan** [comment]
@AlexandrZl  can you elaborate a little more

**Comment by AlexandrZl** [comment]
@Thavarajan sure!

First of all, I created a method of the api to upload an image. The method uploads images to `assets/images`, also I created a method of client side (angular) for it.

My steps:

1. I tried to upload an image
2.The server successfully saved it
3.The client side received a response with the path of new image, e.g., `/assets/images/test.jpg`

Exp. result:
The image is available for client side

Act. result:
`localhost:4200/assets/images/test.jpg` returns a 404 error

It should be noted that images are available after rebuilding app

So, if you need more details I'll provide some parts of my code

**Comment by AlexandrZl** [comment]
any news?
