### ISSUE TITLE
Running server with foreverjs

### ISSUE THREAD

**Issue by newkillerbeast2017** [DavideViolante/Angular-Full-Stack#133]
Just wondering how to set this package up with foreverjs? I have installed foreverjs in my project now, what command do I need to run? Is it `forever npm run prod`? Or do I need to include it programmatically?

**Comment by DavideViolante** [comment]
I don't know what you need foreverjs for, but I think you should replace `nodemon` (in dev script) and `node` (in prod script) in the `package.json` with `forever start`. Then you can run `npm run dev` or `npm run prod` and it will use forever.

**Comment by newkillerbeast2017** [comment]
@DavideViolante thanks for the tip! I just want to use foreverjs to run the app in the background continuously on my server. Do you think there is a better of achieving this rather than foreverjs?

**Comment by Thavarajan** [comment]
@newkillerbeast2017  instead of foreverjs try [pm2 ](http://pm2.keymetrics.io/)which is more elegant
