### ISSUE TITLE
no such file ... index.html

### ISSUE THREAD

**Issue by momoadeli** [DavideViolante/Angular-Full-Stack#134]
(very recent fork, macOS, Angular 5, angular-cli: 1.5.4, node v8.9.1, npm v5.5.1):

Hi, I'm seeing an issue I'm not sure how to address or whether it's specific to how package.json is configured.
When I execute 'npm run dev' at cmd line I get the following errors (application still runs, however):
with fresh machine start I get perpetual:

```
Error: ENOENT: no such file or directory, stat:'..index.html'
on and on and on....
```
Seems the error msgs are the result of line 36 in app.ts. Namely:
`res.sendFile(path.join(__dirname, '../public/index.html'));`

Many thanks!

**Comment by kidbanker** [comment]
Did you solve your issue sir ??
