### ISSUE TITLE
mapbox-gl 

### ISSUE THREAD

**Issue by abubakarmani1** [DavideViolante/Angular-Full-Stack#136]
I am using [mapbox](https://www.npmjs.com/package/@types/mapbox-gl)  which is working fine in dev mode but the moment I run : npm run prod. My project stop showing maps whereas the mapbox is loading properly and the API's of mapbox-gl are returning data as per desired. 

@DavideViolante kindly let me know if i need to update configuration in core files.

here is my code:

/maps.component.ts

`
import { Component, OnInit, AfterViewInit } from '@angular/core';
import * as mapboxgl from 'mapbox-gl';
import * as MapboxGeocoder from 'mapbox-gl-geocoder';
import { MapService } from '../../services/map.service';

@Component({
  selector: 'app-maps',
  templateUrl: './maps.component.html',
  styleUrls: ['./maps.component.scss']
})

export class MapsComponent implements OnInit {
    constructor(private mapService: MapService) {
              }
    ngOnInit() {
       this.isLoading = false;
       this.isEditing = false;
     }
   ngAfterViewInit() {
      var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/outdoors-v9',
    center: [11.05224609375, 52.50953477032727],
    minZoom: 5
  });

  // code to appear a search bar on maps
  map.addControl(new MapboxGeocoder({
    accessToken: environment.mapbox.accessToken
  }));
  var nav = new mapboxgl.NavigationControl();
  map.addControl(nav, 'top-right');
   }
}
`

output
<img width="1194" alt="screen shot 2017-12-02 at 1 35 16 pm" src="https://user-images.githubusercontent.com/12659497/33513598-985c56c8-d767-11e7-8cd3-7ed2e7804807.png">
:

I have mapbox-gl error [#4359 (comment)](https://github.com/mapbox/mapbox-gl-js/issues/4359#issuecomment-303880888) for exact reason. Workarounds in [#4359 (comment)](https://github.com/mapbox/mapbox-gl-js/issues/4359#issuecomment-286277540) and [#4359 (comment)](https://github.com/mapbox/mapbox-gl-js/issues/4359#issuecomment-288001933).

how can i implement these workarounds in the project???

**Comment by NTPLThavarajan** [comment]
hi @abubakarmani1  
instead of that solution did you try this

[Importing with webpack and es6](https://github.com/mapbox/mapbox-gl-js/issues/4368)

**Comment by Thavarajan** [comment]
hi @abubakarmani1
instead of that solution did you try this

[Importing with webpack and es6](https://github.com/mapbox/mapbox-gl-js/issues/4368)

**Comment by DavideViolante** [comment]
Try `ng eject` to eject the webpack config of angular cli.
https://github.com/angular/angular-cli/wiki/eject

**Comment by abubakarmani1** [comment]
All done! thank you @Thavarajan 

solution worked for me
