### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by Paul75** [DavideViolante/Angular-Full-Stack#141]
Hello,

I have a error with last version : when execute have : 

```
Uncaught ReferenceError: Popper is not defined
    at scripts.bundle.js:13
```

Thanks

**Comment by DavideViolante** [comment]
Try this: https://github.com/twbs/bootstrap/issues/24648#issuecomment-342439355
and anyway it should not happen with latest version of the project and Bootstrap 4.
