### ISSUE TITLE
Is there a way to reach the static files like localhost/file instead of localhost/assets/file?

### ISSUE THREAD

**Issue by cenkozan** [DavideViolante/Angular-Full-Stack#147]
I am trying to use a template but it needs to reach the files through localhost not localhost/assets. In my instance, I can't reach the files if I don't write /assets before them.

Thank you for the answer and have a nice year.

**Comment by DavideViolante** [comment]
Try editing this line: https://github.com/DavideViolante/Angular-Full-Stack/blob/master/.angular-cli.json#L11
But I never tried.

**Comment by cenkozan** [comment]
Thank you!
