### ISSUE TITLE
"bootstrap": "^4.0.0-beta.3" problem for running project

### ISSUE THREAD

**Issue by omkarsutar** [DavideViolante/Angular-Full-Stack#149]
I was having this issue while running:
https://github.com/angular/angular-cli/issues/9020

And I FIXED it by:
1. From "bootstrap": "^4.0.0-beta.3" to "bootstrap": "4.0.0-beta.2", take out "^"
2. Deleted package-lock.json
3. and npm i.

Issue Solved!!

**Comment by bjornharvold** [comment]
Not a solution though. Bootstrap 4 beta 3 doesn't play nice with Angular CLI.

**Comment by DavideViolante** [comment]
Actually in the project there is this line that should install exactly that version:
`"bootstrap": "4.0.0-alpha.5",`

Anyway thank you for reporting this issue, I just updated the project with CLI 1.6.4 that shoud fix this issue, let me know.
