### ISSUE TITLE
Webpack Compiled successful But no output

### ISSUE THREAD

**Issue by nithinkumarhere** [DavideViolante/Angular-Full-Stack#152]
Hey,

I was building up some stuff on your boiler plate suddenly i got an issue where i couldn't see anything on the browser when i give "npm run dev" . It shows completely white blank and more interesting thing is, it show in console "webpack compiled successfully". can you help we that stuck with this for so many days couldn't resolve what it is.

**Comment by DavideViolante** [comment]
When you run`npm run dev` and the last message in console is `webpack: Compiled successfully.`, there should be already an opened browser window at `localhost:4200` with the app running. If this doesn't happen, I think there should be some error somewhere. When you see the blank page, try opening the browser console and check if there are some errors.

**Comment by nithinkumarhere** [comment]
Yep, I fixed it because of JWT token which is not removed in the local storage of the previous session. it remained a blank screen. Thanks, Man!

**Comment by amalnathsathyan** [comment]
How to remove that ? That didnt solve it for me !

**Comment by DavideViolante** [comment]
Try to check if you have a token in localstorage and clean it.
https://www.leadshook.com/help/how-to-clear-local-storage-in-google-chrome-browser/
