### ISSUE TITLE
How to verify prod?

### ISSUE THREAD

**Issue by AmirGilboa** [DavideViolante/Angular-Full-Stack#153]
I started the project a few months back and only this week updated to angular 5.
when running **npm run prod**, what is the expected outcome?
files are being generated, but browser is not opened.  should it?
last line on my console is: 
Angular full stack listening on port 3000

how can i verify that the prod version, in dist folder, is running correctly?

and another small thing: before the upgrade, 5 js files used to be created. scripts, polifills, etc. 
one of them was vendor.xxx.bundle.js  . this file is not generated any more. is this by design, or i have a problem? I guess all 3rd party components would go there.
I don't have a hosting server yet, so i have to find a way to test the prod version.

**Comment by DavideViolante** [comment]
Just open in your browser localhost:3000, it's normal that is not opened automatically (only ng serve opens it with the --open command).
More info you will find useful:
- https://github.com/DavideViolante/Angular-Full-Stack/wiki
- https://github.com/angular/angular-cli/wiki#additional-commands
- https://github.com/DavideViolante/Angular-Full-Stack#deploy-heroku

**Comment by AmirGilboa** [comment]
wow, amazing. thank you!
