### ISSUE TITLE
Unknown error from PostCSS plugin...

### ISSUE THREAD

**Issue by AmirGilboa** [DavideViolante/Angular-Full-Stack#155]
This is actually a solved issue. i'm writing here just because it took me 2 days to solve, and maybe someone else is having the same pain.
with the latest cli 1.6.6, angular 5.2.2, bootstrap 4.0.0, npm run prod game me the dreaded 
"Unknown error from PostCSS plugin. Your current PostCSS version is 6.0.16..." and the build breaks.
so a (temp?) solution is found here:
https://stackoverflow.com/questions/48034051/bootstrap-4-beta-3-throws-error-with-angular-cli/48200514#48200514

in node_module, go to bootstrap, package.json, find 'browserslist', and delete the first 2 lines.

"browserslist": [
"last 1 major version", <----- delete this line
">= 1%", <----- delete this line
"Chrome >= 45",
"Firefox >= 38",
"Edge >= 12",
"Explorer >= 10",
"iOS >= 9",
"Safari >= 9",
"Android >= 4.4",
"Opera >= 30"
],

Hope this helps ;)

**Comment by marshallcool** [comment]
same mistake

**Comment by DavideViolante** [comment]
I just updated to Angular CLI v1.7.0 and [it should solve](https://github.com/angular/angular-cli/releases/tag/v1.7.0) the issue. I just tried and it works.
