### ISSUE TITLE
Connected to MongoDB on undefined:undefined

### ISSUE THREAD

**Issue by hevilp** [DavideViolante/Angular-Full-Stack#156]
All is running fine, but I get the message in the console:
`[3] [nodemon] starting `node dist/server/app.js`
[3] Connected to MongoDB on undefined:undefined
[3] Angular Full Stack listening on port 3000`

**Comment by AmirGilboa** [comment]
and mongodb operations work? weird. 
anyways, this is obviously the code in app.ts in your server folder, follow there to find out why these values are empty. i would check your .env file, i think this is where these values are taken from. the mongodb url and port. 
i would look at this line:

let mongodbURI;
if (process.env.NODE_ENV === 'test') {
  mongodbURI = process.env.MONGODB_TEST_URI;
} else {
  mongodbURI = process.env.MONGODB_URI;     <<< check this line!
  app.use(morgan('dev'));
}

**Comment by hevilp** [comment]
All is working fine. I use a fresh clone of the git, you should have the same if you do so

**Comment by DavideViolante** [comment]
I can confirm that but it doesn't affect the funcionality, it's just a wrong console.log.

**Comment by hevilp** [comment]
Yes, I think its why the db variable is not defined, I remember it worked in Version of September or Oktober....
