### ISSUE TITLE
Question: Where does the collections name is defined

### ISSUE THREAD

**Issue by hevilp** [DavideViolante/Angular-Full-Stack#157]
Hi,

sorry that I need to ask, but I cannot find the place, where the name of the collection is defined.
For users its users and for cats, cats. But in which file is it int the code?

Thank you very much.

**Comment by hevilp** [comment]
No, there are is only the server and the database. The collections seems to be named by the name of the service or or controller or like that.

**Comment by dougal83** [comment]
Oh OK then. 'Server/models' the collections are named there I believe.

**Comment by DavideViolante** [comment]
The collections are named based on the model name if I remember correctly
https://github.com/DavideViolante/Angular-Full-Stack/blob/master/server/models/cat.ts#L9

**Comment by hevilp** [comment]
Thanks mate!
