### ISSUE TITLE
how to change port on prod?

### ISSUE THREAD

**Issue by AmirGilboa** [DavideViolante/Angular-Full-Stack#158]
i'm hosting my site in digital ocean. anybody has any guide to this?

I uploaded the site, server is running fine, but the client can't reach the api's.
there are more angular websites on this server, and i suspect that port 3000 is taken.
i want to use another port.
changing the server to user another port is easy. either in app.ts, change the default, 
or better, add PORT: 3001 to the .env file.
but where do i tell the client where to look for the server api?
i guess it goes to localhost:3000/api/cats/... etc.
but i could not find any place to set that. 
Any idea?

**Comment by DavideViolante** [comment]
I think you are looking for this file: `proxy.conf.json`
