### ISSUE TITLE
Maintain separate data for each users 

### ISSUE THREAD

**Issue by felixchristo** [DavideViolante/Angular-Full-Stack#159]
I could see cat data even if it is not entered by me. Cat data is visible to all.  How to maintain separate data for each and every users so that I can see only my datas?

**Comment by dougal83** [comment]
Customise the db schema and queries to filter appropriately.  A self development exercise.

**Comment by felixchristo** [comment]
Do I need to change anything in Base.js or only in schema?

**Comment by dougal83** [comment]
The base is just general and you're customising cats, so just cats schema I would think.

**Comment by felixchristo** [comment]
ok

**Comment by DavideViolante** [comment]
Dup of https://github.com/DavideViolante/Angular-Full-Stack/issues/145
