### ISSUE TITLE
Logout ExpressionError

### ISSUE THREAD

**Issue by Chriscxa** [DavideViolante/Angular-Full-Stack#165]
First: Login,
Open Console,
And Logout!

Error:
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'.

**Comment by DavideViolante** [comment]
Duplicate of https://github.com/DavideViolante/Angular-Full-Stack/issues/105
