### ISSUE TITLE
Unused HttpClient?

### ISSUE THREAD

**Issue by fenixn** [DavideViolante/Angular-Full-Stack#169]
I ran into this error after starting up the app in dev mode:
ERROR in client/app/services/auth.service.ts(19,29): error TS2304: Cannot find name 'HttpClient'.

HttpClient seems to be set for http in the constructor for the AuthService, but it was not imported. However, it didn't seem like it was used. So rather than importing HttpClient, I deleted the line and the app seems to work without it. Was this a mistake? Should I import it instead?

**Comment by DavideViolante** [comment]
I think you have an old version of Angular installed. Try `npm i`. HttpClient is new.

**Comment by fenixn** [comment]
ng -v shows me version 5.2.0

What I mean is in the client/app/services/auth.service.ts file, the line to import HttpClient is missing from the file. However, it is being called in the constructor for AuthService. This causes an error when I try the npm run dev command. I can import HttpClient by adding:

import { HttpClient } from '@angular/common/http';

However, reading the code for the file, it doesn't look like HttpClient is actually being used. So I'm thinking you meant to delete the private http: HttpClient line from the AuthService constructor but forgot to.

**Comment by DavideViolante** [comment]
Oh I see, yes you are right. Thank you for reporting, I removed it.
