### ISSUE TITLE
Error in dist folder creation

### ISSUE THREAD

**Issue by Santhamani** [DavideViolante/Angular-Full-Stack#171]
ENOTEMPTY: directory not empty, rmdir 'E:\Projects\Projects\angularfullstack)\dist\server'

How to create dist folder( client side and server side ) manually?

**Comment by DavideViolante** [comment]
The dist folder is created automatically and you should not create it manually. The errors seems like that the dist folder is not empty or something like that. Try removing it, it should be recreated when you build the app.
