### ISSUE TITLE
NullInjectorError: No provider for JwtHelperService!

### ISSUE THREAD

**Issue by Anil-bohorya** [DavideViolante/Angular-Full-Stack#173]
Getting error in auth.service.ts

```
Error: StaticInjectorError(AppModule)[AuthService -> JwtHelperService]: 
  StaticInjectorError(Platform: core)[AuthService -> JwtHelperService]: 
    NullInjectorError: No provider for JwtHelperService!
    at _NullInjector.get (core.js:994)
    at resolveToken (core.js:1292)
    at tryResolveToken (core.js:1234)
    at StaticInjector.get (core.js:1102)
    at resolveToken (core.js:1292)
    at tryResolveToken (core.js:1234)
    at StaticInjector.get (core.js:1102)
    at resolveNgModuleDep (core.js:10836)
    at _createClass (core.js:10881)
    at _createProviderInstance$1 (core.js:10847)
```

**Comment by dougal83** [comment]
Only issue I can spot is that HttpClientModule is not imported as per the [usage notes](https://github.com/auth0/angular2-jwt/tree/v1.0#usage).

Not sure if JwtHelper being private will cause this issue though.  It is public on the example by module author.

**Comment by timelf123** [comment]
Looks like it was removed here https://github.com/DavideViolante/Angular-Full-Stack/pull/166/commits/b025cf97d7e11cf2043b7d3e13d43c4798c55eb2 because it was not being used after imported. 

My working config includes this:
```
HttpClientModule,
    JwtModule.forRoot({
      config: {
        tokenGetter: tokenGetter ...
```

**Comment by DavideViolante** [comment]
When do you receive this error? I cannot reproduce it neither in dev nor prod.
I only found this: https://stackoverflow.com/questions/44675373/error-error-no-provider-for-jwthelper

**Comment by Anil-bohorya** [comment]
It working Fine now.. I have taken fresh pull and installed. There are few changes in auth service and now JwtHelperService is replaced with JwtModule. 

Thank you guys for all your valuable comments.
