### ISSUE TITLE
Is this project has good structure?

### ISSUE THREAD

**Issue by sameercodes** [DavideViolante/Angular-Full-Stack#175]
I am a beginner to this stack, i want to grab one particular good structure, whether? this app is good structure for production based angular + node apps? or any other suggestion? 🤔

**Comment by Kaffiend** [comment]
The only thing i see lacking structure wise, that i would like to see implemented, is Inversion of Control (dependency injection) with controllers, services, and repositories but this is a starter seed, not a full scale enterprise framework of a seed so one could argue (valid at that), that those types of implementation details are best left to the developer consuming this seed. Great starting point though.

**Comment by timelf123** [comment]
@Kaffiend regarding IOC/dep injection -I enjoyed this article https://www.slalom.com/thinking/typescript-nodejs-enterprise-patterns - uses [InjersifyJS](https://github.com/inversify/InversifyJS) to do IOC

**Comment by Kaffiend** [comment]
That is a very good article, and a solid implementation. I build my closed source professional APIs adding socket.io in a similar pattern with more of a micro service approach. I hope to one day release an open source version of it.

**Comment by sameercodes** [comment]
Thanks

**Comment by Kaffiend** [comment]
@timelf123 Maybe if @DavideViolante doesnt mind, I can issue a PR to the server implementation that includes all this mentioned above.

**Comment by Kaffiend** [comment]
@timelf123 A while back i updated a project and removed typeorm because i only needed mongodb, but i also added socket.io with IoC container.
https://github.com/Kaffiend/enterprise-node-typescript

**Comment by timelf123** [comment]
@Kaffiend I'm sure @DavideViolante wouldn't mind a PR :) If nothing else it will serve as a good base for anyone who wants to accomplish IoC
