### ISSUE TITLE
ORM Decision

### ISSUE THREAD

**Issue by Kaffiend** [DavideViolante/Angular-Full-Stack#176]
@DavideViolante This is just a question issue. I'm curious about your decision, wanting a full typescript stack, as to why you chose mongoose? Previous experience with the library etc.? Have you heard of [Iridium](https://github.com/SierraSoftworks/Iridium) which feels a little more the Typescript way, personally in my opinion. I have no ties to Iridium and am not advertising. Though advocating as a personal consumer of it, yes. I too have built a full stack with it but unfortunately those sources are closed with my company for the time being. Inversify might be of some interest to you as well, if you are not fully aware and chose to leave it out in the interest of simplicity.

**Comment by DavideViolante** [comment]
Actually I don't have that much experience so I choose Mongoose since it is the most used in general and I  used it once. Consider that at the beginning this project had not Typescript on backend but plain Javascript.
I didn't know about Iridium, thank you for the suggetion.

**Comment by timelf123** [comment]
Thanks @Kaffiend I have never heard of Iridium but it looks interesting, along with TypeORM for relational (also supports mongodb apparently)

**Comment by Paul75** [comment]
For me I suggest to use TypeOrm (it can use mongoodb, Mysql, postgresql....)

**Comment by dougal83** [comment]
I agree with ORM, it's friendlier for people from C# background anyway.  It
adds flexibility to choose DB platform but that would technically
facilitate a non-MEAN project.
