### ISSUE TITLE
Uploading file or image

### ISSUE THREAD

**Issue by felixchristo** [DavideViolante/Angular-Full-Stack#179]
Can any one tell me how to upload image or image in this project?

**Comment by timelf123** [comment]
Pick a storage backend, local or cloud. If local, see this tutorial which uses multer on the backend https://ciphertrick.com/2016/10/24/file-upload-with-angular2-nodejs/

If uploading directly to AWS - this works well https://github.com/tensult/ng2-s3-upload

**Comment by felixchristo** [comment]
I am storing it in MongoDB

**Comment by AmirGilboa** [comment]
or just use cloudinary.com.  free for up to 300,000 images (!). like, do you have more than that?
