### ISSUE TITLE
Configuration manager for the server

### ISSUE THREAD

**Issue by gremo** [DavideViolante/Angular-Full-Stack#182]
How to manage the configuration for the server? I.e. having a config module which works fine with typescript?

**Comment by dougal83** [comment]
Are you looking for something more than the dotenv package?  It stores server side variables in the [.env file](https://github.com/DavideViolante/Angular-Full-Stack/blob/master/.env)

**Comment by gremo** [comment]
I already use dotenv, but I was looking for something "more advanced" (i.e. configuration merging). AFAIK dontenv is good for sensitive data (passwords, tokens), but it would be a no-sense storing hundered of configuration keys as environment variables, do you agree?

Of course, something that is compatibile with this project.

**Comment by dougal83** [comment]
Yeah, dotenv is good for keeping secrets(excluded from commits).  The most involved config tooling that I'm aware of is [node-convict](https://github.com/mozilla/node-convict).
