### ISSUE TITLE
postcss-loader

### ISSUE THREAD

**Issue by oshri** [DavideViolante/Angular-Full-Stack#189]
Hi,
I try to use scss in my project. and i get error

ERROR in ./client/styles.scss (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./client/styles.scss)

Module build failed:
[1] @import 'styles-variables';
[1] ^
[1]       File to import not found or unreadable: styles-variables.
[1]       client/styles.scss (line 1, column 1)

**Comment by oshri** [comment]
I also add this lines in angular.json
and don't work :(

"schematics": {
        "@schematics/angular:component": {
          "prefix": "cd",
          "styleext": "scss"
        },
        "@schematics/angular:directive": {
          "prefix": "cd"
        }
      }

**Comment by tc9011** [comment]
@oshri you can try this command:
```shell
npm i node-sass --save
```
