### ISSUE TITLE
How to run project on AWS EC2 instance?

### ISSUE THREAD

**Issue by skaka0190** [DavideViolante/Angular-Full-Stack#192]
I make instance on AWS EC2 server. Installed mongo and upload my project file on AWS. I don't know how to run project on server. I did following steps 
   1. go to my project 
   2. run command npm install 
   3. then run command npm  run dev.
When I run this command project not run. Can you suggest me how to run project on AWS.

**Comment by DavideViolante** [comment]
You surely need to follow step 8-9-10 here https://github.com/DavideViolante/Angular-Full-Stack#deploy-heroku
The 9th step will build the app on the server, so after that you will be able to execute `npm start` on the server. You shouldn't run npm run dev on a remote server, this command is only used on local environment.
So summarizing:
- npm i
- ng build
- npm start
