### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by felipe1033** [DavideViolante/Angular-Full-Stack#201]
Hello Davide Violante, Everything good My name is Felipe, I'm creating a project similar to yours, so instead of being a cats registry it's a client's registry I wanted to know your could put your name on it because your project helped me a lot,

Att. Felipe Tomaz Rebeca, age 13, parents brazil.

**Comment by DavideViolante** [comment]
This is a public project with MIT license, you can use it, leaving unmodified the LICENSE file.
https://github.com/DavideViolante/Angular-Full-Stack/blob/master/LICENSE

**Comment by felipe1033** [comment]
in line 10 of the deploy article (heroku) how can I create real remote server?

**Comment by DavideViolante** [comment]
You can on mlab.com

**Comment by felipe1033** [comment]
Thanks, is there any documentary that teaches to create this server?, Because I do not know how to make rsrs !!!
