### ISSUE TITLE
How to test the server in Postman

### ISSUE THREAD

**Issue by issamsolid** [DavideViolante/Angular-Full-Stack#217]
i am really sorry if my question is look silly  , i am newbie with mean stack i tried endpoints  in postman but show nothing and i can't figure out why... i want consume the API in mobile application

**Comment by Ankita1996** [comment]
You should add the whole link in the postman choose if its post/get. The return data should be chosen as JSON (raw). If it has any input parameters then will need to be added in body of postman and then try to hit it.

**Comment by DavideViolante** [comment]
When the app is running, the server is listening on port 3000, so you can simply call, for example, http://localhost:3000/api/cats
