### ISSUE TITLE
Not able to run on docker compose

### ISSUE THREAD

**Issue by manojantony32** [DavideViolante/Angular-Full-Stack#225]
Getting below issue while running on docker-compose up. Help me with this issue.
![Screenshot 2020-07-05 at 8 33 08 AM](https://user-images.githubusercontent.com/7334423/86524634-5a73c900-be9a-11ea-8a47-c7adf593e595.png)

**Comment by DavideViolante** [comment]
It's a WARN, the app should run correctly anyway, does it work at localhost:3000?
If it doesn't work, try to remove [this line](https://github.com/DavideViolante/Angular-Full-Stack/blob/master/package.json#L26) from package json and run docker compose again.

**Comment by manojantony32** [comment]
Thanks @DavideViolante, now its working fine.
