### ISSUE TITLE
How to expose port 80 in production?

### ISSUE THREAD

**Issue by RonAlmog** [DavideViolante/Angular-Full-Stack#230]
i'm moving my project (based on afs) from 'manual' hosting to docker.
i am using an image called nginx-proxy, that is handling the nginx creation and ssl licenses for you.
The thing is, it has a requirement: you need to expose port 80. in your docker-compose.yml you need this:
expose:
  - 80

as you know, we expose port 3000, and usually use nginx to 'convert' that to 80. 
in my case, i need the be able to expose port 80 from our code. Any idea how to do that?

**Comment by DavideViolante** [comment]
I think you can specify in .env file a new variable called PORT=80 that will be used [here](https://github.com/DavideViolante/Angular-Full-Stack/blob/master/server/app.ts#L11)

**Comment by RonAlmog** [comment]
great, thanks!
