### ISSUE TITLE
Upgrade Bootstrap to v5

### ISSUE THREAD

**Issue by DavideViolante** [DavideViolante/Angular-Full-Stack#243]
https://getbootstrap.com/docs/5.0/migration/

**Comment by mudassarlodhi** [comment]
@DavideViolante are you working on it?? if not i can take this task

**Comment by DavideViolante** [comment]
I'm not currently working on it. Yea if you want you can take the task, thank you!

**Comment by mudassarlodhi** [comment]
> I'm not currently working on it. Yea if you want you can take the task, thank you!



> I'm not currently working on it. Yea if you want you can take the task, thank you!

awesome i,ll start working on it. Select me as an assignee
