### ISSUE TITLE
Add a dockerfile

### ISSUE THREAD

**Issue by Chabane** [DavideViolante/Angular-Full-Stack#28]
Hello,

Thanks for sharing,

It would be even better if you add a dockerfile. Jenkinsfile (for CI/CD)?

**Comment by DavideViolante** [comment]
I should study Docker a little bit. I don't know it yet, sorry.

**Comment by Chabane** [comment]
For sure,

You have an example here : https://nodejs.org/en/docs/guides/nodejs-docker-webapp/

**Comment by simon-hardy** [comment]
This might be a good start:

process.yml
```

apps:
  - script   : 'dist/server/app.js'
    name     : 'Website'
    exec_mode: 'cluster'
    instances: 0
```

Dockerfile
```
FROM node:7

RUN npm install @angular/cli -g
RUN npm install pm2 -g

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY . /usr/src/app/
RUN npm install
RUN ng build -aot -prod 
RUN tsc -p server

EXPOSE 4443

CMD ["pm2-docker", "process.yml"]
```

**Comment by adwulfran** [comment]
@simon-hardy 
You need to include MongoDB image in your Dockerfile, am I right?

**Comment by adwulfran** [comment]
@simon-hardy
You also need to include MongoDB image in your Dockerfile. Am I right ?
