### ISSUE TITLE
Intergration with live-reload/ browser-sync 

### ISSUE THREAD

**Issue by midhunadarvin** [DavideViolante/Angular-Full-Stack#32]
Consider using a live-reload plugin to speed up development. To see the updated file changes by auto-reloading the browser.

**Comment by DavideViolante** [comment]
Yes, this is something in my todo list, but I don't know how to accomplish it. `ng serve` has it built in, but this project doesn't use `ng serve` to be executed.
I found livereload.com but it needs also an extension to the browser if I'm correct.

**Comment by midhunadarvin** [comment]
What is your opinion about [browser-sync](https://browsersync.io/) . Do you think we can set it up with gulp or grunt?

**Comment by DavideViolante** [comment]
Keep in mind I want to keep this project as simpler as possible. I don't want to add gulp or grunt or similar. Angular itself has the autoreload into the `ng serve` command, I'd like to use that one in this project too, somehow.
I think Angular autoreload is accomplished using webpack, as the logs says when you update a file while `ng serve is runnig`
```webpack: Compiled successfully.
webpack: Compiling...
```

**Comment by DavideViolante** [comment]
I made it work on branch `autoreload` but it's a bit tricky.
- I ran `ng eject` (see [wiki](https://github.com/angular/angular-cli/wiki/eject))
- I edited webpack.config and added proxy for BE server
- I edited start script on package.json

Now autoreload works, but I don't like this solution so much tbh.

**Comment by midhunadarvin** [comment]
I have made it work with [ng serve](https://github.com/angular/angular-cli/wiki/serve) and [opn-cli](https://github.com/sindresorhus/opn-cli) . But i have implemented it in the `server-ts` branch. Can you see if it works as a clean solution?

**Comment by DavideViolante** [comment]
Yeah, this is what I made some weeks ago (https://github.com/DavideViolante/Angular2-Full-Stack/commit/8c8701837104ebeae23966f3b138919d4b1520ef) too! I just noticed that now it works good because, thanks to you, the proxy config only applies to `/api` path and not to `/` (that causes 404 on refresh). I applied the change on master, thank you.
ps. opn is not necessary, just use `--open` on cli.
