### ISSUE TITLE
Why do you use this import syntax in TypeScript?

### ISSUE THREAD

**Issue by fairydhwen** [DavideViolante/Angular-Full-Stack#41]
Why do you use :
`import * as bodyParser from 'body-parser';` and not `import { * } from './....'; ` syntax ?
Also i dont understand why no `export class` ?

It looks like it's just a JS to TS transpilation.

**Comment by MarkPieszak** [comment]
When you're doing something like that it's because it's a commonJS module, and isn't `export`'ing things itself, so you need to just pull down the whole thing.

It's the TS equivalent of `var bodyParser = require('body-parser');`
