### ISSUE TITLE
Cannot find folder public after running dev

### ISSUE THREAD

**Issue by ppprevost** [DavideViolante/Angular-Full-Stack#42]
when i do npm run dev :
the folder server is created within the folder dist. But cannot find the folder public. 

However, it's with npm run prod both server and public are created. 
So the application does'nt work in dev environment :(

**Comment by DavideViolante** [comment]
https://github.com/DavideViolante/Angular-Full-Stack/issues/40
https://github.com/DavideViolante/Angular-Full-Stack/issues/35

**Comment by ppprevost** [comment]
thx
