### ISSUE TITLE
Can't add CSS for directive

### ISSUE THREAD

**Issue by huynhtuanhuy** [DavideViolante/Angular-Full-Stack#43]
How can i add CSS for a directive, in example navbar.
I try to create new file "navbar.css" in folder navbar but it not work.
Tks a lot :(

**Comment by DavideViolante** [comment]
The navbar is into app.component.html, so it will use app.component.scss. If you created a new directive using Angular CLI (`ng g directive name-directive`), it should automatically create the style file too.

**Comment by huynhtuanhuy** [comment]
Tks for your help, but angular cli seem not work for me :(
![image](https://cloud.githubusercontent.com/assets/22828048/25259200/ef0bfa50-266e-11e7-944d-e031b36cd14a.png)

**Comment by DavideViolante** [comment]
Is that a problem related to my project?
Anyway I found this https://github.com/angular/angular-cli/issues/5661
