### ISSUE TITLE
How to debug the app in WebStorm?

### ISSUE THREAD

**Issue by rlach** [DavideViolante/Angular-Full-Stack#63]
I'm trying to figure out how to debug application based on this starter using WebStorm. I tried using --debug flag for nodemon in package.json then connecting with Node.js Remote Debug configuration. Even though it connected the code won't stop on breakpoints. I can go with --inspect but:
* it's not integrated with IDE
* I don't want to work on javascript code

Also, I couldn't manage to make IDE work with debugging angular part of the application.

**Comment by ImOmi** [comment]
@rlach did you figure it out?

**Comment by stephenharper82** [comment]
@rlach  and @ImOmi  - any luck getting debug working in WebStorm? Cheers.

**Comment by rlach** [comment]
I've been preoccupied with other projects and never got around to it.

**Comment by stherrienaspnet** [comment]
If you want to debug the server side code with WebStorm here is screen captures that show how I do it.
I start server with debug icon and type in terminal npm run dev_no_server
Hoping this could help someone

![debug_server_config](https://user-images.githubusercontent.com/6126961/34882141-9a42e0d8-f783-11e7-8bb3-4abbe0b23d44.png)
![debug_start](https://user-images.githubusercontent.com/6126961/34882147-9d5d4466-f783-11e7-90c7-ba714b34ff08.png)
![npm_dev_no_server](https://user-images.githubusercontent.com/6126961/34882149-9f9ade0a-f783-11e7-8461-b4da6bd59fc1.png)
