### ISSUE TITLE
How to connect to different DB

### ISSUE THREAD

**Issue by pinyaras** [DavideViolante/Angular-Full-Stack#65]
HI,
I already have a existing database (MongoDB).
How can i modify your code to work with my DB?

Thank you :)

**Comment by DavideViolante** [comment]
Yes, you can use an existing MongoDB database. Read here the wiki here:
https://github.com/DavideViolante/Angular-Full-Stack/wiki#how-to-use-a-remote-mongodb-server

**Comment by pinyaras** [comment]
Thanks

**Comment by pinyaras** [comment]
How about if i had SQL DB?

**Comment by DavideViolante** [comment]
The project uses Mongoose that is made for MongoDB database. Changing the whole project to use SQL is a *big* change and I don't recommend you that.

**Comment by rainstormza** [comment]
@pinyaras 
I use mssql library in my project.

[](https://github.com/patriksimek/node-mssql)

I forked Angular-Full-Stack and change DB from mongo to sql server everything work fine.

**Comment by pinyaras** [comment]
@rainstormza 
Thank you kub, I really appreciate your help
