### ISSUE TITLE
backend models, in front app?

### ISSUE THREAD

**Issue by AmirGilboa** [DavideViolante/Angular-Full-Stack#66]
Great project!
Is there a way to use the models that are defined in backend, like cats, users,  also in the front end?
for example, the cat.service will return a list of cats, not 'any'.
I guess i could add the models on the client app, but that would not be very DRY, right?

**Comment by DavideViolante** [comment]
That's a great question. I made a research and the first results here are interesting:
https://www.google.com/search?q=mongoose+models+in+frontend
In particular:
- http://mongoosejs.com/docs/unstable/docs/browser.html
You can find this phrase:
> When you include the mongoose.js file in a script tag, mongoose will attach a **mongoose object to the global window**. This object includes a Schema constructor that you can use to define schemas much like in NodeJS.

I never tried it, but I think it deserves a try.

**Comment by AmirGilboa** [comment]
ok, thanks. i will also read these links.  👍
