### ISSUE TITLE
request to add fileUpload and date to the project. 

### ISSUE THREAD

**Issue by aruribadraiah** [DavideViolante/Angular-Full-Stack#72]
Dar Davide,
Could you please add another two fields  1. file upload  and 2. date picker to this project. if possible.
( this required front+back end logic ).

**Comment by RonAlmog** [comment]
for file upload there are several popular choices, like this one that i use:
https://www.npmjs.com/package/ng2-file-upload

works great for most use cases. they even support file drop. read more here:
https://github.com/valor-software/ng2-file-upload/tree/master

**Comment by RonAlmog** [comment]
Regarding date picker, I suggest ng-bootstrap. that is a swiss army knife that contain many useful components like date picker, modal, accordion, carousel, tabs, and many more, all based on the latest bootstrap.
@DavideViolante , i think this can be very useful. let me know if you want a pull request.

**Comment by aruribadraiah** [comment]
Thanks I will get back to you if any problem in implimenting
