### ISSUE TITLE
disabling buttons based on roles

### ISSUE THREAD

**Issue by ray2233** [DavideViolante/Angular-Full-Stack#77]
Hi,
I am new to Angular, my question is that if I want to disable the edit and delete button for regular 'users' and enable these buttons only for 'Admin' how would I do that? Could you send me a function for that? I would really appreciate your help

Thanks!!

**Comment by DavideViolante** [comment]
Import auth into the ts file and in the html add this to the button
`[disabled]="auth.currentUser.role === 'user'"`
it should work

**Comment by RonAlmog** [comment]
that will work of course. but @ray2233 , if you want a production grade system, you should also protect your api endpoints, because people might go to them directly, and not through your gui.
check this for help on how to do that: https://github.com/DavideViolante/Angular-Full-Stack/issues/58

**Comment by ray2233** [comment]
Great thanks!! I will try it
