### ISSUE TITLE
Procfile

### ISSUE THREAD

**Issue by aag0121** [DavideViolante/Angular-Full-Stack#78]
Hello David,
one question: Why you are not using a [Procfile](https://devcenter.heroku.com/articles/procfile) document? 

I can't deploy without it, I receive an error application on Heroku. If you will have to use it, what did you put inside, something like: _web: node ./dist/server/server.js_ ?

**Comment by DavideViolante** [comment]
Mmh yes I think I forgot it. The content should be:
`web: node dist/server/app.js`

let me know.

**Comment by aag0121** [comment]
Your app is working in Heroku, but not my app (I based on this scaffolding) that's **work in my local system** but not in Heroku, I don't know why I follow  your steps to deploy. I remember some weeks ago that you have a _server.js_ , in the back-end of my app I have a _server.js_ and also an _app.ts_ that could be cause the error in heroku but i'm not pretty sure. Do you have please 2 minutes [to take a look](https://github.com/aag0121/barterAPP/tree/master/BarterAPP-Browser/server) ? 

I can 

Many thanks in advance.

**Comment by aag0121** [comment]
Yes, work with this Procfile.
