### ISSUE TITLE
dependent drop down list help in angular 2

### ISSUE THREAD

**Issue by aruribadraiah** [DavideViolante/Angular-Full-Stack#79]
I have collection  countries  and having two fields  state and city
countries:  {country:'INDIA',city:'HYD'},
                 {country:'INDIA',city:'delhi'},
                 {country:'USA',city:'PITSBURG'},
                 {country:'USA',city:'NEWYORK'};
html file
Ist drop down
<div class="form-group">
 <select class="form-control" name="courtry" formControlName="courtry">
<option *ngFor="let country of countries">{{courtry.country}}</option>
</select>        
   </div>
2nd Dropdown
<div class="form-group">
 <select class="form-control" name="city" formControlName="city">
<option *ngFor="let city of countries ">{{city.city}}</option>
</select>        
   </div>
My second dropdown should come filtered one by selecting option in Ist dropdown  by country 
I request to give logic code behind this.

**Comment by RonAlmog** [comment]
This kind of questions will be better answered in websites like stackoverflow. Here we focus on questions that are directly related to the project. thanks.
