### ISSUE TITLE
Dependent dropdown list help

### ISSUE THREAD

**Issue by aruribadraiah** [DavideViolante/Angular-Full-Stack#80]
kindly help for how to resolve two dependent drop downs
Ist dropdown
<select name="country" formControlName="country">
<div *ngFor="let county in countys">{{country.name}}</div>
  </select>
2nd dropdown list
<select name="city" formControlName="city">
<div *ngFor="let city in countys | filterBy: ">{{city.name}}</div>
</select>
2nd dropdown should be filtered depending on Ist dropdown , kindly code required for this.
thank and regards.

**Comment by DavideViolante** [comment]
This is not stackoverflow. You can only ask questions or report issues about this project.
