### ISSUE TITLE
404 on server

### ISSUE THREAD

**Issue by dbarochia** [DavideViolante/Angular-Full-Stack#84]
I have created build using ng build -prod and when I move files from dist folder to actual server it always throw 404 error(api not found)
I believe when we build it only bundle app related asset not api. I am having azure web services where I would like to move application code.
Can you please let me know, what will be the best way to bundle api along with application so that work on live site.

Error: http://websitename.com/api/cats 404 (Not Found)

**Comment by jamesnik** [comment]
I think your web server not set proxy to api and port for node should 3000. Sorry for my english not very good.
