### ISSUE TITLE
Dist & Lib not generating

### ISSUE THREAD

**Issue by jmrapp1** [DavideViolante/Angular-Full-Stack#85]
I had to clean and delete the `dist` and `lib` folder which were generated before, but now they will not regenerate. Any idea why? I'm using the standard `npm run dev`

**Comment by DavideViolante** [comment]
The dist folder is created with npm run prod.
https://github.com/DavideViolante/Angular-Full-Stack/wiki

**Comment by jmrapp1** [comment]
I ended up actually just running `tsc` and it compiled it all for me. When running `npm run dev` it points to the `dist` folder, so when it's not there it throws errors. Thanks!
