### ISSUE TITLE
upload  function not found problem in app.ts file

### ISSUE THREAD

**Issue by aruribadraiah** [DavideViolante/Angular-Full-Stack#86]
Dear Davide
I am using file upload, app.js file is ok, but app.ts file is throwing err ( upload not found )
server/app.ts(51,9): error TS2304: Cannot find name 'upload'.
pl. advise me.
`let storage = multer.diskStorage({ //multers disk storage settings
        destination: function (req, file, cb) {
            cb(null, './uploads/');
        },
        filename: function (req, file, cb) {
            const datetimestamp = Date.now();
            cb(null, file.fieldname + '-' + datetimestamp + '.' + file.originalname.split('.')[file.originalname.split('.').length -1]);
        }
    });

   let upload = multer({ //multer settings
                    storage: storage
                }).single('file');

    /** API path that will upload the files */

    app.post('/upload', function(req, res) {
        upload(req,res,function(err){
            console.log(req.file);
            if(err){
                 res.json({error_code:1,err_desc:err});
                 return;
            }
            res.json({error_code:0,err_desc:null});
       });
    });
`

**Comment by DavideViolante** [comment]
Not related to my project..
