### ISSUE TITLE
when npm start occur the issue cannot find module /......./dist/server/app.js

### ISSUE THREAD

**Issue by Huang9495** [DavideViolante/Angular-Full-Stack#88]
## **My operation environment:**
system: Ubuntu 14.04
node.js: v6.11.0
mongodb: 3.0.15

## **The error is here:**
Error: Cannot find module '/home/kris-allen/Angular-Full-Stack/dist/server/app.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular2-full-stack@4.0.0 start: `node dist/server/app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-full-stack@4.0.0 start script 'node dist/server/app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-full-stack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node dist/server/app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-full-stack
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-full-stack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/kris-allen/Angular-Full-Stack/npm-debug.log

# **Who can help me resolve the issue???**

**Comment by DavideViolante** [comment]
As the readme says, you should use `npm run dev` or `npm run prod` instead of `npm start`

**Comment by Huang9495** [comment]
Hi! @DavideViolante I have resolve the issue! Thank you for you help!
