### ISSUE TITLE
upload file problem

### ISSUE THREAD

**Issue by aruribadraiah** [DavideViolante/Angular-Full-Stack#90]
Dear Davide,
I am able to upload file on local m/c , but from client it is not doing, and my cors section in app.ts file is like this , so pl. guide me how to resolve this problem.

`app.use(function(req, res, next) { //allow cross origin requests
        res.setHeader("Access-Control-Allow-Methods", "POST, PUT, OPTIONS, DELETE, GET");
        res.header("Access-Control-Allow-Origin", "http://www.xx.xx.xx.xx:3000");
 //       res.header("Access-Control-Allow-Origin", "http://localhost:3000");
        res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
        res.header("Access-Control-Allow-Credentials", true);
        next();
thank in advance.

    });
`

**Comment by DavideViolante** [comment]
Not related to my project.
