### ISSUE TITLE
How to implement the long distance transmission between two computer????

### ISSUE THREAD

**Issue by Huang9495** [DavideViolante/Angular-Full-Stack#91]
1.I want to trans data from my client of computer to other service of computer in same LAN , and both computer working in Angular-Full-Stack
2.I don't know what file I should edit and where I have to deit?
3.my operate environment :Ubuntu14.04; node.js6.11;
4.who can tell me how to do? Thanks ! Thanks! Thanks!

**Comment by dougal83** [comment]
I'd advise that you read [this book](https://www.ng-book.com/2/) or ask somewhere appropriate like https://stackoverflow.com/.

Good luck bud.

**Comment by Huang9495** [comment]
@dougal83 thanks
