### ISSUE TITLE
Loading problem

### ISSUE THREAD

**Issue by divyashobana19** [DavideViolante/Angular-Full-Stack#92]
Program is working fine...In localhost:4200 the output is coming as below,
![image](https://user-images.githubusercontent.com/25704038/28659443-217b64f8-72cd-11e7-8ec4-a8b932b74187.png)
When i am submitting also,it is not saving.

**Comment by xadhix** [comment]
Check if "localhost:3000/api/cats" works. If it doesn't, then the node server didn't start properly. Check console for errors. And these type of questions are more suitable for StackOverflow.

**Comment by DavideViolante** [comment]
Seems like the backend or the db is not running. What command did you use to run the app?

**Comment by divyashobana19** [comment]
I used ng serve command

**Comment by DavideViolante** [comment]
Read the readme of this repo.

**Comment by divyashobana19** [comment]
I tried in npm run dev and npm run prod but also iam getting the above error.

**Comment by DavideViolante** [comment]
Show me the console output after running npm run dev.

**Comment by divyashobana19** [comment]
Now its working fine.
Thanks DavideViolante
