### ISSUE TITLE
how to use many collections in this code?

### ISSUE THREAD

**Issue by Mean563** [DavideViolante/Angular-Full-Stack#93]
hi @DavideViolante , I had one question, now I am using : 

`mongodb://localhost:27017/DB-Name/Collecction-Name `

But If i want different Collection names, How can I implement this kind of code. 
Could you please help me !!

**Comment by ppprevost** [comment]
Actually you could use different collection name with mongoose.
Thanks to mongoose schema you could create a new collection (exemple user, cat etc..) and automatically your collection will be created on Mongo Db. 
 see the model part : Angular-Full-Stack/server/models/
to create a new document you need to instantiate wi th the new keyword 

see insert method in Angular-Full-Stack/server/controllers/base.ts

**Comment by Mean563** [comment]
@ppprevost  Thank you so much.I got it. I lose my head like anything. Thank you so much..
