### ISSUE TITLE
set relative path from node_modules files into index.html 

### ISSUE THREAD

**Issue by Mean563** [DavideViolante/Angular-Full-Stack#95]
Hi @DavideViolante , need small help, I added into ng-prime to node modules, but i am not able to access the file names in index.html 

i am just using `"./node_modules/primeng/resources/primeng.min.css"`

but it is not loading into browser 
getting below error in browser : `GET http://localhost:4200/node_modules/primeng/resources/themes/omega/theme.css `

could you please help me how to set relative path I am using same folder structure !

Thanks in advance !!!

**Comment by DavideViolante** [comment]
Did you edit the `.angular-cli.json` file line 22-24? Add primeng css to that array, so it gets loaded.
